# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import translation_pb2 as translation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in translation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslationServiceStub(object):
    """Translation service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/translation.TranslationService/Translate',
                request_serializer=translation__pb2.TranslateRequest.SerializeToString,
                response_deserializer=translation__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.BatchTranslate = channel.unary_unary(
                '/translation.TranslationService/BatchTranslate',
                request_serializer=translation__pb2.BatchTranslateRequest.SerializeToString,
                response_deserializer=translation__pb2.BatchTranslateResponse.FromString,
                _registered_method=True)
        self.GetCacheStats = channel.unary_unary(
                '/translation.TranslationService/GetCacheStats',
                request_serializer=translation__pb2.CacheStatsRequest.SerializeToString,
                response_deserializer=translation__pb2.CacheStatsResponse.FromString,
                _registered_method=True)
        self.ClearCache = channel.unary_unary(
                '/translation.TranslationService/ClearCache',
                request_serializer=translation__pb2.ClearCacheRequest.SerializeToString,
                response_deserializer=translation__pb2.ClearCacheResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/translation.TranslationService/HealthCheck',
                request_serializer=translation__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=translation__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TranslationServiceServicer(object):
    """Translation service definition
    """

    def Translate(self, request, context):
        """Translate a single text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchTranslate(self, request, context):
        """Translate multiple texts in batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStats(self, request, context):
        """Get cache statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCache(self, request, context):
        """Clear cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=translation__pb2.TranslateRequest.FromString,
                    response_serializer=translation__pb2.TranslateResponse.SerializeToString,
            ),
            'BatchTranslate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchTranslate,
                    request_deserializer=translation__pb2.BatchTranslateRequest.FromString,
                    response_serializer=translation__pb2.BatchTranslateResponse.SerializeToString,
            ),
            'GetCacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStats,
                    request_deserializer=translation__pb2.CacheStatsRequest.FromString,
                    response_serializer=translation__pb2.CacheStatsResponse.SerializeToString,
            ),
            'ClearCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCache,
                    request_deserializer=translation__pb2.ClearCacheRequest.FromString,
                    response_serializer=translation__pb2.ClearCacheResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=translation__pb2.HealthCheckRequest.FromString,
                    response_serializer=translation__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'translation.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('translation.TranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationService(object):
    """Translation service definition
    """

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/Translate',
            translation__pb2.TranslateRequest.SerializeToString,
            translation__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchTranslate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/BatchTranslate',
            translation__pb2.BatchTranslateRequest.SerializeToString,
            translation__pb2.BatchTranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/GetCacheStats',
            translation__pb2.CacheStatsRequest.SerializeToString,
            translation__pb2.CacheStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/ClearCache',
            translation__pb2.ClearCacheRequest.SerializeToString,
            translation__pb2.ClearCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/HealthCheck',
            translation__pb2.HealthCheckRequest.SerializeToString,
            translation__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
